spring:
  application:
    name: core-api

  profiles:
    active: local

  config:
    import:
      - logging.yml
      - db-core.yml

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: live
